# Generated by Django 2.0.3 on 2018-05-04 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_transfusion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfusion',
            old_name='profile',
            new_name='user',
        ),
    ]
