# Generated by Django 2.0.3 on 2018-05-04 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20180504_0848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfusion',
            old_name='user',
            new_name='profile',
        ),
    ]
