# Generated by Django 2.0.3 on 2018-05-04 16:17

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20180504_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfusion',
            name='user',
        ),
        migrations.AddField(
            model_name='transfusion',
            name='profile',
            field=models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to='homepage.Profile'),
        ),
    ]
