# Generated by Django 2.0.3 on 2018-05-04 16:28

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homepage', '0007_auto_20180504_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfusion',
            name='profile',
        ),
        migrations.AddField(
            model_name='transfusion',
            name='user',
            field=models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
