# Generated by Django 2.0.3 on 2018-05-04 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_auto_20180504_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfusion',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.Profile'),
        ),
    ]
