# Generated by Django 2.0.3 on 2018-05-04 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_auto_20180504_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfusion',
            name='user',
        ),
        migrations.AddField(
            model_name='transfusion',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.Profile'),
        ),
    ]
