# Generated by Django 2.0.3 on 2018-03-29 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilization', '0002_auto_20180327_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
