# Generated by Django 2.1.7 on 2019-03-15 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilization', '0003_auto_20180329_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrn', models.IntegerField(default=-1)),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transfusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_product', models.CharField(default='', max_length=100)),
                ('issue_time', models.DateTimeField()),
                ('transfusions_on_day', models.IntegerField(default=-1)),
                ('din', models.CharField(default='', max_length=20)),
                ('num_units', models.IntegerField(default=-1)),
                ('product', models.CharField(default='', max_length=20)),
                ('test_type', models.CharField(default='', max_length=20)),
                ('test_result', models.CharField(default='', max_length=20)),
                ('test_accession', models.CharField(default='', max_length=20)),
                ('test_time', models.DateTimeField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfusions', to='utilization.Location')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfusions', to='utilization.Patient')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfusions', to='utilization.Provider')),
            ],
        ),
        migrations.AddField(
            model_name='provider',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='utilization.Specialty'),
        ),
    ]
